### ISSUE TITLE
CMS 5.1 compatibility

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/recipe-ccl#11]
Is there an ETA when this will become updated to work with CMS 5.1 recipe? Thanks.

Also should the default branch be changed to `3`?

**Comment by ChloeSartorelli** [comment]
Official support for this recipe was dropped with 5.0.0 as [noted in the changelog](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#modules-not-supported-going-forward), so the CMS Squad won't be making any changes to it from here on.

**Comment by michalkleiner** [comment]
So what are the expectations/assumptions for people on CCL (former CWP) on how to get to CMS 5.1?

**Comment by ChloeSartorelli** [comment]
My recommendation would be to [inline the recipe](https://github.com/silverstripe/recipe-plugin?tab=readme-ov-file#inlining-recipes) but I don't know that there was any thought put into that when the decision was made to drop support.
@maxime-rainville thoughts?

**Comment by ChloeSartorelli** [comment]
Gonna close this as we won't be making a new release for it - Max can add any additional information if he wants to.
